version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 40
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
